version: "3.9"

services:
  strongtype:
    image: strongtype:latest
    volumes:
      - ./:/project
    build:
      context: .
      dockerfile: Dockerfile
    # execute bash in running container
    stdin_open: true # docker run -i
    tty: true        # docker run -t